### ISSUE TITLE
20180918 Evening

### ISSUE THREAD

**Issue by Mauriyin** [DrFishHUST/WhereToeat#1]
How about going to Huimian for eating tonight?

**Comment by lizekang** [comment]
No,it's too bad.

**Comment by lizekang** [comment]
How about xi'an? I think liangpi package is great.

**Comment by lizekang** [comment]
@ShengeBelmendo

**Comment by DrFishHUST** [comment]
liangpi package have raised price recent days.

**Comment by Mauriyin** [comment]
Just eat liangpi packet few days ago, where is qiying?

**Comment by Mauriyin** [comment]
Why not Dongbei cuisine? Long time no eat.

**Comment by WqyJh** [comment]
North-East cuisine is ok!

**Comment by DrFishHUST** [comment]
Dongbei cuisine is ok.

**Comment by lizekang** [comment]
ojbk

**Comment by Mauriyin** [comment]
That's all right. I will close this issue!
