### ISSUE TITLE
20180920 Dinner

### ISSUE THREAD

**Issue by Mauriyin** [DrFishHUST/WhereToeat#7]
where to eat a？

**Comment by Mauriyin** [comment]
@WqyJh @lizekang @DrFishHUST

**Comment by lizekang** [comment]
how about Fashion city?

**Comment by lizekang** [comment]
@WqyJh

**Comment by Mauriyin** [comment]
What is Fashion city？

**Comment by importpandas** [comment]
Wqy went to Gast gym just now.

**Comment by Mauriyin** [comment]
Lj wqy, we can invite wangjie?

**Comment by importpandas** [comment]
Why not take the little sister for dinner Qiao-mi-mi-ly?

**Comment by lizekang** [comment]
hahahha

**Comment by Mauriyin** [comment]
Empty Island it was
